In [1]:
# Creating a 2D array using numpy

import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
print(twoDArray)


[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [2]:
# Inserting

newTwoDArray = np.insert(twoDArray, 1, [[1,2,3,4]], axis=0)      # axis = 0 means row
print(newTwoDArray)                                              # axis = 1 means column


[[11 15 10  6]
 [ 1  2  3  4]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [3]:
# Accessing an element

def accessElements(array, rowIndex, colIndex):
    if rowIndex >= len(array) and colIndex >= len(array[0]):
        print('Incorrect Index')
    else:
        print(array[rowIndex][colIndex])

accessElements(newTwoDArray, 1, 2)

3


In [4]:
# Traversing in 2D array

def traverseTDArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])


traverseTDArray(twoDArray)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [3]:
# searching an element
import numpy as np
twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])

def searchTDArray(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'The value is located index '+str(i)+" "+str(j)
    return 'The element no found'


print(searchTDArray(twoDArray, 11))

The value is located index 0 0


In [4]:
# Deleting 

newTDArray = np.delete(twoDArray, 1, axis=1)
print(newTDArray)

[[11 10  6]
 [10 11  5]
 [12 12  8]
 [15 14  9]]
